MEDIA_TARGET_BOARD_PLATFORM=y
AUDIO_GAIN_TOOLCHAIN_OF_AARCH64=y
MEDIA_TARGET_PLATFORM=buildroot
CEDARX_EXTRA_CXXFLAGS = -DCONF_H265_4K
CEDARC_EXTRA_CXXFLAGS += -DCONF_USE_IOMMU -D__LINUX__
TINA_CHIP_TYPE = T527
VE_OFFSET = 0
