MEDIA_TARGET_BOARD_PLATFORM=y
AUDIO_GAIN_TOOLCHAIN_OF_ARM=y
CEDARC_EXTRA_CXXFLAGS += -DCONF_USE_IOMMU -D__LINUX__
TINA_CHIP_TYPE = T113-i
VE_OFFSET = 0

# for linux5.4, which update di_v1xx drv.
CONF_DI_V1XX = y
