MEDIA_TARGET_BOARD_PLATFORM=y
AUDIO_GAIN_TOOLCHAIN_OF_ARM=y
TINA_CHIP_TYPE = T113_S4P
AUDIO_GAIN_PLATFORM_OF_BUILDROOT=y
CEDARC_EXTRA_CXXFLAGS += -DCONF_USE_IOMMU -D__LINUX__
VE_OFFSET = 0

# for linux5.4, which update di_v1xx drv.
CONF_DI_V1XX = y
