MEDIA_TARGET_BOARD_PLATFORM=y
AUDIO_GAIN_TOOLCHAIN_TYPE_OF_RISCV=y
CEDARX_EXTRA_CXXFLAGS = -DCONF_H264_4K -DCONF_H265_4K
CEDARC_EXTRA_CXXFLAGS += -DCONF_USE_IOMMU -D__LINUX__
TINA_CHIP_TYPE = D1
VE_OFFSET = 0
